### ISSUE TITLE
There is no secrets.yml

### ISSUE THREAD

**Issue by chandleryang76** [SDM2016Friends/Assignment2#3]
I wonder there is no secrets.yml in sprint0 branch.
Is there any special reason for leaving out the file?

**Comment by allenzhong** [comment]
Because some .yml file such as secrets.yml and database.yml are local environment-related, people often create them by themselves. 
You could check .gitignore file where both secrets.yml and database.yml were ignored.

**Comment by allenzhong** [comment]
you could create a new secret.yml or copy from another project. Then execute `rake secret` and copy the token to your secret.yml.

**Comment by chandleryang76** [comment]
Yeah, you're right.
but, I am thinking about auto-build in Travis CI and automatically deploy it on Heroku. 
I am wondering how to generate secrets.yml  automatically to deploy it.

**Comment by allenzhong** [comment]
this file will be generated on Heroku, don't worry.
But I'm not sure it could be generated by Travis CI, I need check

**Comment by chandleryang76** [comment]
Oh, thanks.
