### ISSUE TITLE
Travis-CI does not pass

### ISSUE THREAD

**Issue by allenzhong** [SDM2016Friends/Assignment2#4]
There are some errors before we accepted pull request.
We have to solve it. Here is a solution we could try.
http://stackoverflow.com/questions/9321153/rails-database-setup-on-travis-ci

**Comment by chandleryang76** [comment]
## Here is example of .travis.yml file

```
language: ruby
rvm:
  - "2.3.0"

script:
- bundle exec rake db:create
- bundle exec rake db:migrate
```

**Comment by chandleryang76** [comment]
I uploaded .travis.yml file because my task is integration between travis and heroku.
The file is on my pull request.

**Comment by allenzhong** [comment]
solved. close it.
